export const START_SAVE = "START_SAVE";
export const COMPLETE_SAVE = "COMPLETE_SAVE";
export const REGISTER_CHANGES = "REGISTER_CHANGES";
export const UNREGISTER_CHANGES = "UNREGISTER_CHANGES";
export const TOGGLE_AUTOSAVE = "TOGGLE_AUTOSAVE";
