export const START_SAVE = "START_SAVE";
export const COMPLETE_SAVE = "COMPLETE_SAVE";
export const REGISTER_VALID_SAVE_STATE = "REGISTER_VALID_SAVE_STATE";
export const REGISTER_INVALID_SAVE_STATE = "REGISTER_INVALID_SAVE_STATE";
export const REGISTER_CHANGES = "REGISTER_CHANGES";
export const UNREGISTER_CHANGES = "UNREGISTER_CHANGES";
export const TOGGLE_AUTOSAVE = "TOGGLE_AUTOSAVE";

export const START_CODE_EXECUTION = "START_CODE_EXECUTION";
export const COMPLETE_CODE_EXECUTION = "COMPLETE_CODE_EXECUTION";

export const START_COMPILATION = "START_COMPILATION";
export const COMPLETE_COMPILATION = "COMPLETE_COMPILATION";

export const SET_CODE_FILE_PANE = "SET_CODE_FILE_PANE";
