export const START_CODE_EXECUTION = "START_CODE_EXECUTION";
export const COMPLETE_CODE_EXECUTION = "COMPLETE_CODE_EXECUTION";

export const START_COMPILATION = "START_COMPILATION";
export const COMPLETE_COMPILATION = "COMPLETE_COMPILATION";

export const SET_CODE_FILE_PANE = "SET_CODE_FILE_PANE";

export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";
export const OPEN_TAB = "OPEN_TAB";
export const CLOSE_TAB = "CLOSE_TAB";

export const OPEN_CODE_FILE = "OPEN_CODE_FILE";
export const CLOSE_CODE_FILE = "CLOSE_CODE_FILE";
export const OPEN_FOLDER = "OPEN_FOLDER";
export const CLOSE_FOLDER = "CLOSE_FOLDER";
export const OPEN_SIDEBAR_STAGE = "OPEN_SIDEBAR_STAGE";
export const CLOSE_SIDEBAR_STAGE = "CLOSE_SIDEBAR_STAGE";
export const OPEN_SIDEBAR_CONTAINER = "OPEN_SIDEBAR_CONTAINER";
export const CLOSE_SIDEBAR_CONTAINER = "CLOSE_SIDEBAR_CONTAINER";
